import { YT, YTNodes } from 'youtubei.js';
import { getInnertube } from '.';
import type {
	ChannelContentPlaylists,
	ChannelContentVideos,
	ChannelOptions,
	ChannelPage,
	Image,
	Video
} from '../model';
import { invidiousItemSchema } from './schema';

export async function getChannelYTjs(channelId: string): Promise<ChannelPage> {
	const innertube = await getInnertube();

	const innerResults = await innertube.getChannel(channelId);

	const authorId = innerResults.metadata.url?.split('/')[4] ?? '';

	let authorBanners: Image[] = [];
	if (innerResults.header?.is(YTNodes.PageHeaderView)) {
		authorBanners = innerResults.header.banner?.image ?? [];
	}

	return {
		type: 'channel',
		allowedRegions: innerResults.metadata.available_countries ?? [],
		tabs: innerResults.tabs.map((tab) => tab.toLowerCase()),
		latestVideos: [],
		isFamilyFriendly: true,
		author: innerResults.metadata.title ?? '',
		authorThumbnails: innerResults.metadata.avatar ?? [],
		authorId: authorId,
		authorBanners,
		joined: 0,
		authorVerified: true,
		totalViews: 0,
		authorUrl: `/channel/${authorId}`,
		subCount: 0,
		autoGenerated: false,
		description: '',
		descriptionHml: ''
	};
}

export async function getChannelContentYTjs(
	channelId: string,
	options: ChannelOptions
): Promise<ChannelContentVideos | ChannelContentPlaylists> {
	const innertube = await getInnertube();

	const channel = await innertube.getChannel(channelId);

	let innerResults: YT.Channel;
	if (options.type === 'videos') {
		innerResults = await channel.getVideos();
	} else if (options.type === 'playlists') {
		innerResults = await channel.getPlaylists();
	} else if (options.type === 'shorts') {
		innerResults = await channel.getShorts();
	} else {
		innerResults = await channel.getLiveStreams();
	}

	const videos: Video[] = [];
	if (innerResults.current_tab?.content?.is(YTNodes.RichGrid)) {
		innerResults.current_tab.content.contents.forEach((item) => {
			if (item.is(YTNodes.RichItem)) {
				const invidiousSchema = invidiousItemSchema(item.content);
				if (invidiousSchema?.type === 'video') {
					invidiousSchema.author = channel.metadata.title ?? '';
					videos.push(invidiousSchema);
				}
			}
		});
	}

	return {
		continuation: '',
		videos
	};
}
