import { cleanNumber, extractNumber } from '$lib/numbers';
import { convertToSeconds } from '$lib/time';
import type { Channel, Playlist, Thumbnail, Video } from '../model';
import { Helpers, YTNodes } from 'youtubei.js';

export function invidiousItemSchema(item: Helpers.YTNode): Video | Channel | Playlist | undefined {
	if (item.is(YTNodes.Video)) {
		const views = extractNumber(item.view_count?.toString() || '');
		return {
			type: 'video',
			title: item.title.toString(),
			videoId: item.video_id,
			viewCountText: cleanNumber(views),
			viewCount: views,
			videoThumbnails: item.thumbnails as Thumbnail[],
			published: 0,
			publishedText: item.published?.toString() || '',
			description: '',
			descriptionHtml: '',
			authorUrl: `/channel/${item.author.id}`,
			authorId: item.author.id,
			authorVerified: false,
			liveNow: false,
			isUpcoming: false,
			premium: false,
			author: item.author.name,
			lengthSeconds: item.length_text?.text ? convertToSeconds(item.length_text.text) : 0
		};
	} else if (item.is(YTNodes.Channel)) {
		return {
			type: 'channel',
			authorId: item.id,
			author: item.author.name,
			authorUrl: `/channel/${item.id}`,
			authorVerified: item.author.is_verified === true,
			subCount: item.video_count.text ? extractNumber(item.video_count.text) : 0,
			totalViews: 0,
			autoGenerated: false,
			description: item.description_snippet.text ?? '',
			descriptionHml: item.description_snippet.toHTML() ?? '',
			authorThumbnails: item.author.thumbnails as Thumbnail[]
		};
	} else if (item.is(YTNodes.LockupView) && item.content_type === 'PLAYLIST') {
		let author = '';
		const metadataRows = item.metadata?.metadata?.metadata_rows[0];
		if (metadataRows && metadataRows.metadata_parts) {
			author = metadataRows.metadata_parts[0].text?.text ?? '';
		}
		return {
			type: 'playlist',
			title: item.metadata?.title.text ?? '',
			playlistId: item.content_id,
			playlistThumbnail: item.content_image?.is(YTNodes.CollectionThumbnailView)
				? item.content_image.primary_thumbnail?.is(YTNodes.ThumbnailView)
					? item.content_image.primary_thumbnail.image[0].url
					: ''
				: '',
			authorVerified: false,
			author,
			authorId: '',
			videoCount: 0,
			videos: []
		};
	} else if (item.is(YTNodes.ShortsLockupView)) {
		let viewCountText = '';
		if (item.overlay_metadata?.secondary_text) {
			viewCountText = item.overlay_metadata.secondary_text.toString();
		}

		const videoId = item.on_tap_endpoint?.command?.is(YTNodes.ReelWatchEndpoint)
			? (item.on_tap_endpoint.command.buildRequest().playerRequest?.videoId ?? '')
			: (item.entity_id?.split('-').pop() ?? '');

		return {
			type: 'shortVideo',
			title: item.overlay_metadata?.primary_text?.toString() ?? '',
			videoId,
			viewCountText,
			videoThumbnails: (item.thumbnail ?? []) as Thumbnail[],
			published: 0,
			publishedText: '',
			description: '',
			descriptionHtml: '',
			authorUrl: '',
			authorId: '',
			authorVerified: false,
			liveNow: false,
			isUpcoming: false,
			premium: false,
			author: '',
			lengthSeconds: 0
		};
	} else if (item.is(YTNodes.LockupView) && item.content_type === 'VIDEO') {
		let publishedText = '';
		let viewCountText = '';
		const rows = item.metadata?.metadata?.metadata_rows;
		if (rows) {
			viewCountText = rows[0]?.metadata_parts?.[0]?.text?.text ?? '';
			publishedText = rows[0]?.metadata_parts?.[1]?.text?.text ?? '';
		}

		const authorId =
			item.metadata?.image?.renderer_context?.command_context?.on_tap?.payload?.browseId || '';

		let lengthSeconds = 0;
		if (item.content_image?.is(YTNodes.ThumbnailView)) {
			item.content_image.overlays.forEach((overlay) => {
				if (overlay.is(YTNodes.ThumbnailBottomOverlayView)) {
					overlay.badges.forEach((badge) => {
						if (
							badge.is(YTNodes.ThumbnailBadgeView) &&
							badge.badge_style === 'THUMBNAIL_OVERLAY_BADGE_STYLE_DEFAULT'
						) {
							lengthSeconds = convertToSeconds(badge.text);
						}
					});
				}
			});
		}

		return {
			type: 'video',
			title: item.metadata?.title.toString() ?? '',
			videoId: item.content_id,
			viewCountText: viewCountText,
			videoThumbnails: (item.content_image?.is(YTNodes.ThumbnailView)
				? item.content_image.image
				: []) as Thumbnail[],
			published: 0,
			publishedText,
			description: '',
			descriptionHtml: '',
			authorUrl: `/channel/${authorId}`,
			authorId,
			authorVerified: false,
			liveNow: false,
			isUpcoming: false,
			premium: false,
			author: '',
			lengthSeconds
		};
	}
}
