import { cleanNumber, extractNumber } from '$lib/numbers';
import { convertToSeconds } from '$lib/time';
import type { Channel, Thumbnail, Video } from '../model';
import { Helpers, YTNodes } from 'youtubei.js';

export function invidiousItemSchema(item: Helpers.YTNode): Video | Channel | undefined {
	if (item.is(YTNodes.Video)) {
		const views = extractNumber(item.view_count?.toString() || '');
		return {
			type: 'video',
			title: item.title.toString(),
			videoId: item.video_id,
			viewCountText: cleanNumber(views),
			viewCount: views,
			videoThumbnails: item.thumbnails as Thumbnail[],
			published: 0,
			publishedText: item.published?.toString() || '',
			description: '',
			descriptionHtml: '',
			authorUrl: `/channel/${item.author.id}`,
			authorId: item.author.id,
			authorVerified: false,
			liveNow: false,
			isUpcoming: false,
			premium: false,
			author: item.author.name,
			lengthSeconds: item.length_text?.text ? convertToSeconds(item.length_text.text) : 0
		};
	} else if (item.is(YTNodes.Channel)) {
		return {
			type: 'channel',
			authorId: item.id,
			author: item.author.name,
			authorUrl: `/channel/${item.id}`,
			authorVerified: item.author.is_verified === true,
			subCount: item.video_count.text ? extractNumber(item.video_count.text) : 0,
			totalViews: 0,
			autoGenerated: false,
			description: item.description_snippet.text ?? '',
			descriptionHml: item.description_snippet.toHTML() ?? '',
			authorThumbnails: item.author.thumbnails as Thumbnail[]
		};
	}
}
