import { cleanNumber, extractNumber } from '$lib/numbers';
import { convertToSeconds } from '$lib/time';
import { getInnertube } from '.';
import { searchSetDefaults } from '../misc';
import type { Channel, SearchOptions, SearchResults, Thumbnail, Video } from '../model';
import { YTNodes, type Types } from 'youtubei.js';

export async function getSearchYTjs(
	search: string,
	options: SearchOptions
): Promise<SearchResults> {
	const innertube = await getInnertube();

	searchSetDefaults(options);

	const innerResults = await innertube.search(search, {
		sort_by: options.sort_by,
		duration: options.duration,
		features: [options.features] as Types.Feature[],
		upload_date: options.date
	});

	const searchResults: SearchResults = [];

	innerResults.results.forEach((result) => {
		if (result.is(YTNodes.Video)) {
			const views = extractNumber(result.view_count?.toString() || '');
			const patchedResult: Video = {
				type: 'video',
				title: result.title.toString(),
				videoId: result.video_id,
				viewCountText: cleanNumber(views),
				viewCount: views,
				videoThumbnails: result.thumbnails as Thumbnail[],
				published: 0,
				publishedText: result.published?.toString() || '',
				description: '',
				descriptionHtml: '',
				authorUrl: `/channel/${result.author.id}`,
				authorId: result.author.id,
				authorVerified: false,
				liveNow: false,
				isUpcoming: false,
				premium: false,
				author: result.author.name,
				lengthSeconds: result.length_text?.text ? convertToSeconds(result.length_text.text) : 0
			};
			searchResults.push(patchedResult);
		} else if (result.is(YTNodes.Channel)) {
			const patchedResult: Channel = {
				type: 'channel',
				authorId: result.id,
				author: result.author.name,
				authorUrl: `/channel/${result.id}`,
				authorVerified: result.author.is_verified === true,
				subCount: result.video_count.text ? extractNumber(result.video_count.text) : 0,
				totalViews: 0,
				autoGenerated: false,
				description: result.description_snippet.text ?? '',
				descriptionHml: result.description_snippet.toHTML() ?? '',
				authorThumbnails: result.author.thumbnails as Thumbnail[]
			};
			searchResults.push(patchedResult);
		}
	});

	return searchResults;
}
