// Not possible to exact from typescript interfaces at runtime.

export const VideoSchema: Record<string, string | string[]> = {
	author: 'string',
	authorId: 'string',
	authorUrl: 'string',
	authauthorVerified: 'string',
	published: 'number',
	publishedText: 'string',
	title: 'string',
	type: ['video', 'shortVideo', 'stream'],
	videoId: 'string',
	viewCount: 'number',
	viewCountText: 'string'
};

export const ChannelSchema: Record<string, string> = {
	author: 'string',
	authorId: 'string',
	authorUrl: 'string',
	authorVerified: 'boolean',
	autoGenerated: 'boolean',
	channelHandle: 'string',
	description: 'string',
	subCount: 'number'
};
